version: '3.8'

services:
  postgres12:
    image: postgres:12
    container_name: postgres12
    environment: 
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    ports: 
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/initdb.d:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres12

volumes:
  db:
    name: pg
  pgadmin:
    name: vpga
